name: Discord Notification

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit message to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
